Models/ErrorViewModel.cs
namespace PriscilaZuniga_Examen1P.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PZClass.cs
using System;

namespace PriscilaZuniga_Examen1P.Models
{
    public class PZClass
    {
        //Creacion de la Clase
        public int ID { get; set; }
        public int Edad { get; set; }
        public decimal PZ_Peso { get; set; }
        public string? PZ_Apodo { get; set; }
        public Boolean PZ_Activo { get; set; }
        public DateTime PZ_FechaNacimiento { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PriscilaZuniga_Examen1P.Models;
using System.Diagnostics;

namespace PriscilaZuniga_Examen1P.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View("PZ_Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PZClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PriscilaZuniga_Examen1P.Models;

namespace PriscilaZuniga_Examen1P.Controllers
{
    public class PZClassController : Controller
    {
        private readonly PriscilaZuniga_DBContext _context;

        public PZClassController(PriscilaZuniga_DBContext context)
        {
            _context = context;
        }
        
        // GET: PZClass
        //Cambios Para el metodo de busqueda
        public async Task<IActionResult> Index(string buscar)
        {
            var classPZ= from PZClass in _context.PZClass select PZClass;
            if (!String.IsNullOrEmpty(buscar))
            {
                classPZ = classPZ.Where(s => s.PZ_Apodo!.Contains(buscar));
            }
            return View(await classPZ.ToListAsync());
        }

        // GET: PZClass/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pZClass = await _context.PZClass
                .FirstOrDefaultAsync(m => m.ID == id);
            if (pZClass == null)
            {
                return NotFound();
            }

            return View(pZClass);
        }

        // GET: PZClass/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PZClass/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Edad,PZ_Peso,PZ_Apodo,PZ_Activo,PZ_FechaNacimiento")] PZClass pZClass)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pZClass);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pZClass);
        }

        // GET: PZClass/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pZClass = await _context.PZClass.FindAsync(id);
            if (pZClass == null)
            {
                return NotFound();
            }
            return View(pZClass);
        }

        // POST: PZClass/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Edad,PZ_Peso,PZ_Apodo,PZ_Activo,PZ_FechaNacimiento")] PZClass pZClass)
        {
            if (id != pZClass.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pZClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PZClassExists(pZClass.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pZClass);
        }

        // GET: PZClass/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pZClass = await _context.PZClass
                .FirstOrDefaultAsync(m => m.ID == id);
            if (pZClass == null)
            {
                return NotFound();
            }

            return View(pZClass);
        }

        // POST: PZClass/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pZClass = await _context.PZClass.FindAsync(id);
            if (pZClass != null)
            {
                _context.PZClass.Remove(pZClass);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PZClassExists(int id)
        {
            return _context.PZClass.Any(e => e.ID == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/PZ_Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Page Created by PriscilaZ</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/PZClass/Create.cshtml
@model PriscilaZuniga_Examen1P.Models.PZClass

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PZClass</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PZ_Peso" class="control-label"></label>
                <input asp-for="PZ_Peso" class="form-control" />
                <span asp-validation-for="PZ_Peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PZ_Apodo" class="control-label"></label>
                <input asp-for="PZ_Apodo" class="form-control" />
                <span asp-validation-for="PZ_Apodo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="PZ_Activo" /> @Html.DisplayNameFor(model => model.PZ_Activo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="PZ_FechaNacimiento" class="control-label"></label>
                <input asp-for="PZ_FechaNacimiento" class="form-control" />
                <span asp-validation-for="PZ_FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/PZClass/Delete.cshtml
@model PriscilaZuniga_Examen1P.Models.PZClass

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PZClass</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PZ_Peso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PZ_Peso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PZ_Apodo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PZ_Apodo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PZ_Activo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PZ_Activo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PZ_FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PZ_FechaNacimiento)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/PZClass/Details.cshtml
@model PriscilaZuniga_Examen1P.Models.PZClass

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>PZClass</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Edad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Edad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PZ_Peso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PZ_Peso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PZ_Apodo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PZ_Apodo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PZ_Activo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PZ_Activo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PZ_FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PZ_FechaNacimiento)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/PZClass/Edit.cshtml
@model PriscilaZuniga_Examen1P.Models.PZClass

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PZClass</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Edad" class="control-label"></label>
                <input asp-for="Edad" class="form-control" />
                <span asp-validation-for="Edad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PZ_Peso" class="control-label"></label>
                <input asp-for="PZ_Peso" class="form-control" />
                <span asp-validation-for="PZ_Peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PZ_Apodo" class="control-label"></label>
                <input asp-for="PZ_Apodo" class="form-control" />
                <span asp-validation-for="PZ_Apodo" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="PZ_Activo" /> @Html.DisplayNameFor(model => model.PZ_Activo)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="PZ_FechaNacimiento" class="control-label"></label>
                <input asp-for="PZ_FechaNacimiento" class="form-control" />
                <span asp-validation-for="PZ_FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/PZClass/Index.cshtml
@model IEnumerable<PriscilaZuniga_Examen1P.Models.PZClass>

@{
    ViewData["Title"] = "Index";
}

<h1>Listado de Personas</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="PZClass" asp-action="Index">
    <p>
        Ingresa el Apodo de la persona: <input type="text" name="buscar" class="form-text"/>
        <input type="submit" value="Buscar" class="btn btn-sm btn-dark"/>

    </p>

</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Edad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PZ_Peso)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PZ_Apodo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PZ_Activo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PZ_FechaNacimiento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Edad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PZ_Peso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PZ_Apodo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PZ_Activo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PZ_FechaNacimiento)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PriscilaZuniga_Examen1P</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PriscilaZuniga_Examen1P.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PriscilaZuniga_Examen1P</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PriscilaZuniga_Examen1P - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>